version: '3'

services:
  #   image: lexferramirez/my-node-api-app:1.0
  #   ports:
  #     - 3000:6000
  web:
    container_name: nodeapi
    restart: always
    build: .
    ports:     
      - "5000:6000"
    links:
      - mongo
    volumes:
      - .:/home/app
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:     
      - "27018:27017"
    volumes:
    #[volume reference]:ruta donde mongo persite la data dentro del contenedor
    #cuando se regenere el contenedor la data de "mongo-data" en el host sera replicada en "/data/db" del contenedor
      - mongo-data:/data/db
volumes: 
  #nombre de la referencia del volumen el cual sera usado en el contenedor
  mongo-data:
    #crea el fisica storage donde se almacenara la informacion
    driver: local